# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7f27eff2f42c6a368550f3b47851685a33397c2ebab425b93aed98ba0d855014c2e303aef0a329bf368ec10a54e24dfce9a16d63f47242cfeb839ae6ce0da2ce

test:
  secret_key_base: 8bdf66cb0cc9c0e6d4b85b26bd75642d5eca1504d2ec2d9848b7c902f53f507351339b665074691faceafe9f0616aa1213fb276b202c741ca895d2df62f042d0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
